kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    commands:
      - echo location-ssh info 8
      - whoami
      - echo $${SSH_PRIVATE_KEY}
      - ssh
      - exit
    secrets:
      - source: SSH_PRIVATE_KEY
          target: SSH_PRIVATE_KEY