kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    volumes:
      - name: ssh-key
        path: /testsky/ssh-key
    commands:
      - echo location-ssh info 10
      - whoami
      - echo $SSH_PRIVATE_KEY
      - touch /testsky/ssh-key/qqqs.pem
      - echo "$SSH_PRIVATE_KEY" > qqqs.pem
      - ls -al /testsky/ssh-key
      - chmod 600 /testsky/ssh-key/qqqs.pem
#      - ssh-keygen -f /testsky/ssh-key/qqqs.pem
      - ssh -i /testsky/ssh-key/qqqs.pem -p 14288 vagrant@0.tcp.ap.ngrok.io "ifconfig;cd /var/www/data/wp_proj;touch runner_access.txt"
volumes:
  - name: ssh-key
    host:
      path: /proj_root/m2_local_env/ssh-key