kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    volumes:
      - name: qqqd
        path: /testsky/ssh
    commands:
      - echo location-ssh info 10
      - whoami
      - echo $SSH_PRIVATE_KEY
      - ls -al /testsky/ssh/vagrant_private_key
#      - chmod 600 /testsky/ssh/vagrant_private_key/vagrant_private_key
#      - ssh-keygen -f /testsky/ssh/vagrant_private_key/vagrant_private_key
#      - ssh -i /testsky/ssh/vagrant_private_key/vagrant_private_key -p 14288 vagrant@0.tcp.ap.ngrok.io "ifconfig;cd /var/www/data/wp_proj;touch runner_access.txt"
volumes:
  - name: qqqd
    host:
      path: /proj_root/m2_local_env/ssh-key