kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: appleboy/drone-ssh
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    volumes:
      - /proj_root/m2_local_env/ssh-key/vagrant_private_key:/root/ssh/drone_rsa
    commands:
      - echo location-ssh info 10
      - whoami
      - echo $SSH_PRIVATE_KEY
      - ssh -i drone_rsa -p 14288 vagrant@0.tcp.ap.ngrok.io ifconfig
      - cd /var/www/data/wp_proj
      - touch runner_access.txt