kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    commands:
      - echo location-ssh info 9
      - whoami
      - echo $SSH_PRIVATE_KEY
      - ssh
      - exit