kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine
    commands:
      - echo location-runner info 4
      - whoami
      - env
      - exit
      - cd /var/www/data/wp_proj
      - touch test_drone_runner.txt
      - exit
    secrets:
      - source: SSH_PRIVATE_KEY
        target: SSH_PRIVATE_KEY