kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    environment:
      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
    volumes:
      - name: prv_key
        path: /root/ssh
    commands:
      - echo location-ssh info 10
      - whoami
      - echo $SSH_PRIVATE_KEY
      - chmod 600 /root/ssh/vagrant_private_key
      - ssh-keygen -c -f /root/ssh/vagrant_private_key
      - ssh -i /root/ssh/vagrant_private_key -p 14288 vagrant@0.tcp.ap.ngrok.io "ifconfig;cd /var/www/data/wp_proj;touch runner_access.txt"
volumes:
  - name: prv_key
    host:
      path: /proj_root/m2_local_env/ssh-key