kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rastasheep/ubuntu-sshd
    commands:
      - echo location-ssh info 4
      - whoami
      - echo "$$SSH_PRIVATE_KEY"
      - sudo echo "$$SSH_PRIVATE_KEY" > $home/.ssh/id_rsa
      - exit
    secrets:
      - source: SSH_PRIVATE_KEY
        target: SSH_PRIVATE_KEY